### ISSUE TITLE
Chef fails when missing group

### ISSUE THREAD

**Issue by colby** [copious-cookbooks/users#9]
Chef fails when theres a user that doesnt not have a group.

```
$ git diff .kitchen.yml
diff --git a/.kitchen.yml b/.kitchen.yml
index e06065e..9295b1c 100644
--- a/.kitchen.yml
+++ b/.kitchen.yml
@@ -26,6 +26,7 @@ suites:
           - bob
           # NOTE: omitting user "carol" for tests
           - dan
+          - dennis
           # NOTE: including user without data bag
         group_list:
           - sudo

$ cat test/integration/data_bags/users/dennis.json
{
    "id": "dennis",
    "action": "create",
    "comment": "Dennis Mennis",
    "ssh_keys": ["ssh-rsa dennis-key"]
}
```

```
       id: dennis: no such user

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/cop_users/recipes/default.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `include?' for nil:NilClass

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/cop_users/recipes/default.rb:90:in `block (2 levels) in from_file'
         /tmp/kitchen/cache/cookbooks/cop_users/recipes/default.rb:86:in `each'
         /tmp/kitchen/cache/cookbooks/cop_users/recipes/default.rb:86:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/cop_users/recipes/default.rb:82:in `each'
         /tmp/kitchen/cache/cookbooks/cop_users/recipes/default.rb:82:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/cop_users/recipes/default.rb:

        83:      # Wipe member_list for each group
        84:      member_list = []
        85:
        86:      users.each do |u|
        87:          user = data_bag_item('users', u)
        88:          # Check that user_list allows user
        89:          if user_list.include?(u)
        90>>             if user['groups'].include?(g)
        91:                  member_list << user['id']
        92:              end
        93:          end
        94:      end
        95:
        96:      # Assign member_list to group
        97:      group g do
        98:          group_name g
        99:          action     :create
```

**Comment by colby** [comment]
Fixed in #10
